### PR TITLE
Initial implementation of DOS clock driver

### PR DESCRIPTION
**Pull request by skiselev**
I wrote a DOS clock driver for the RTC8088 board, with configurable I/O port in the 200h-3FFh range. 
It intentionally does not support 70h address, as that would be supported by 8088 BIOS on Micro 8088 and similar, but it is very likely that I/O access to ports below 100h on ISA bus will not work on other systems.

I'd appreciate if you'll test it and merge

### CODE REVIEW

**Comment by explit7** [comment]
Somehow it doesnt work for me atm. My RTC8088 3.0 is configured to OFF OFF OFF = 0x70. 
Its recognized by the Micro8088 BIOS
Other DIP Switches doenst work on my Micro8088.
GETRTC / SETRTC recognises the RTC on the Port $2C0
DSCLOCK.SYS doenst recognise the RTC on Port 0x2CO

Any suggestions what i else can try? @skiselev , @spark2k06 ?

Thanks

**Comment by skiselev** [comment]
That's weird. It works just fine on my system with either ports 0x240 or 0x2C0.
Is it possible that you have another device at port 0x2C0 or nearby?
Also, it was a bug in the earlier version of the SPLD code that @spark2k06 fixed here
 https://github.com/spark2k06/RTC8088/commit/2afaaf758ae2926f3695502ad3d355191d1d4a33
Can you please check that you're using the latest SPLD code, or just try a different I/O address.
dsclock_port_0x2C0

**Comment by spark2k06** [comment]
It works perfectly. Tested ports 0x240, 0x2c0 and 0x70, no problem. I merge the changes, thanks @skiselev! Just a suggestion, maybe you can add an autodetect I/O port option.

**Comment by explit7** [comment]
Somehow it does not work for me.
I flashed the latest SPLD on a new ATF16V8B Chip.
It is recognized by the Micro8088 BIOS only when i set the DIP-Switches to On On On or Off Off Off.
Otherwise it is not recognized.
DSCLOCK.SYS doesnt recognize it when i use Autodetection or when i use the Parameter 0X2C0
GET_RTC and SET_RTC recognized it on Port 02c0.
Very weird.

I have usual Micro8088 System with following Carts:
XTIDE, Adlib Card, Cycle Logic CGA-Graphic Card, 2xSerial, 1xParallel Controller 16C552, RTC8088 3.0

Any suggestions, what else i can test?

RTC1
RTC2
RTC3

**Pull request merged**
